### ISSUE TITLE
Turborepo?

### ISSUE THREAD

**Issue by izakfilmalter** [team-nimble/smd#1]
Would be nice to see turborepo support rather that yarn workspaces. Also, long time no chat @corysimmons. We should catch up some time.

**Comment by corysimmons** [comment]
haha, hey Izak, long time!

I'm actually thinking of turning this into one of those `examples/with-xyz` repos so I can commit working experiments. Turborepo can be on that list.

I'll close this when I do that.

**Comment by corysimmons** [comment]
I couldn't figure out how to do the whole `examples/with-turborepo` thing (eslint and tsconfig tricky stuff in monorepos 😩 ), so I just made a new branch.

It works though and is pretty fast! https://github.com/team-nimble/smd/tree/turborepo `yarn && yarn dev`. Web on http://localhost:3000

**Comment by izakfilmalter** [comment]
Sweet, will take a look.
